targets = {
   "Abilities":"http://virt10.itu.chalmers.se/index.php/Abilities",
   "Ability Losses":"http://virt10.itu.chalmers.se/index.php/Ability_Losses",
   "Abstract Player Construct Development":"http://virt10.itu.chalmers.se/index.php/Abstract_Player_Construct_Development",
   "Abstract Player Constructs":"http://virt10.itu.chalmers.se/index.php/Abstract_Player_Constructs",
   "Access Rewards":"http://virt10.itu.chalmers.se/index.php/Access_Rewards",
   "Achievements":"http://virt10.itu.chalmers.se/index.php/Achievements",
   "Achilles' Heels":"http://virt10.itu.chalmers.se/index.php/Achilles%27_Heels",
   "Action Caps":"http://virt10.itu.chalmers.se/index.php/Action_Caps",
   "Action Programming":"http://virt10.itu.chalmers.se/index.php/Action_Programming",
   "Actions Have Diegetically Social Consequences":"http://virt10.itu.chalmers.se/index.php/Actions_Have_Diegetically_Social_Consequences",
   "Actor Detachment":"http://virt10.itu.chalmers.se/index.php/Actor_Detachment",
   "Adventures":"http://virt10.itu.chalmers.se/index.php/Adventures",
   "Agents":"http://virt10.itu.chalmers.se/index.php/Agents",
   "AI Players":"http://virt10.itu.chalmers.se/index.php/AI_Players",
   "Aim & Shoot":"http://virt10.itu.chalmers.se/index.php/Aim_%26_Shoot",
   "Alarms":"http://virt10.itu.chalmers.se/index.php/Alarms",
   "Algorithmic Agents":"http://virt10.itu.chalmers.se/index.php/Algorithmic_Agents",
   "Alien Space Bats":"http://virt10.itu.chalmers.se/index.php/Alien_Space_Bats",
   "Alignment":"http://virt10.itu.chalmers.se/index.php/Alignment",
   "Alternate Reality Gameplay":"http://virt10.itu.chalmers.se/index.php/Alternate_Reality_Gameplay",
   "Altruistic Actions":"http://virt10.itu.chalmers.se/index.php/Altruistic_Actions",
   "Always Vulnerable":"http://virt10.itu.chalmers.se/index.php/Always_Vulnerable",
   "Ambiguous Responses":"http://virt10.itu.chalmers.se/index.php/Ambiguous_Responses",
   "Ammunition":"http://virt10.itu.chalmers.se/index.php/Ammunition",
   "Analysis Paralysis":"http://virt10.itu.chalmers.se/index.php/Analysis_Paralysis",
   "Anonymous Actions":"http://virt10.itu.chalmers.se/index.php/Anonymous_Actions",
   "Area Control":"http://virt10.itu.chalmers.se/index.php/Area_Control",
   "Arenas":"http://virt10.itu.chalmers.se/index.php/Arenas",
   "Arithmetic Progression":"http://virt10.itu.chalmers.se/index.php/Arithmetic_Progression",
   "Armor":"http://virt10.itu.chalmers.se/index.php/Armor",
   "Artifact-Location Proximity":"http://virt10.itu.chalmers.se/index.php/Artifact-Location_Proximity",
   "Asymmetric Gameplay":"http://virt10.itu.chalmers.se/index.php/Asymmetric_Gameplay",
   "Asymmetric Goals":"http://virt10.itu.chalmers.se/index.php/Asymmetric_Goals",
   "Asymmetric Starting Conditions":"http://virt10.itu.chalmers.se/index.php/Asymmetric_Starting_Conditions",
   "Asynchronous Collaborative Actions":"http://virt10.itu.chalmers.se/index.php/Asynchronous_Collaborative_Actions",
   "Asynchronous Gameplay":"http://virt10.itu.chalmers.se/index.php/Asynchronous_Gameplay",
   "Attention Demanding Gameplay":"http://virt10.itu.chalmers.se/index.php/Attention_Demanding_Gameplay",
   "Auto-Aim":"http://virt10.itu.chalmers.se/index.php/Auto-Aim",
   "Auxiliary Game Screens":"http://virt10.itu.chalmers.se/index.php/Auxiliary_Game_Screens",
   "Avatars":"http://virt10.itu.chalmers.se/index.php/Avatars",
   "Awareness of Surroundings":"http://virt10.itu.chalmers.se/index.php/Awareness_of_Surroundings",
   "Back-to-Back Game Sessions":"http://virt10.itu.chalmers.se/index.php/Back-to-Back_Game_Sessions",
   "Backseat Gamers":"http://virt10.itu.chalmers.se/index.php/Backseat_Gamers",
   "Backtracking Levels":"http://virt10.itu.chalmers.se/index.php/Backtracking_Levels",
   "Bag Building":"http://virt10.itu.chalmers.se/index.php/Bag_Building",
   "Bag Management":"http://virt10.itu.chalmers.se/index.php/Bag_Management",
   "Balancing Effects":"http://virt10.itu.chalmers.se/index.php/Balancing_Effects",
   "Bases":"http://virt10.itu.chalmers.se/index.php/Bases",
   "Beat the Leader":"http://virt10.itu.chalmers.se/index.php/Beat_the_Leader",
   "Betrayal":"http://virt10.itu.chalmers.se/index.php/Betrayal",
   "Betting":"http://virt10.itu.chalmers.se/index.php/Betting",
   "Bidding":"http://virt10.itu.chalmers.se/index.php/Bidding",
   "Big Dumb Objects":"http://virt10.itu.chalmers.se/index.php/Big_Dumb_Objects",
   "Bluffing":"http://virt10.itu.chalmers.se/index.php/Bluffing",
   "Bookkeeping Tokens":"http://virt10.itu.chalmers.se/index.php/Bookkeeping_Tokens",
   "Boss Monsters":"http://virt10.itu.chalmers.se/index.php/Boss_Monsters",
   "Budgeted Action Points":"http://virt10.itu.chalmers.se/index.php/Budgeted_Action_Points",
   "Cameras":"http://virt10.itu.chalmers.se/index.php/Cameras",
   "Campaigns":"http://virt10.itu.chalmers.se/index.php/Campaigns",
   "Camping":"http://virt10.itu.chalmers.se/index.php/Camping",
   "Capture":"http://virt10.itu.chalmers.se/index.php/Capture",
   "Card Building":"http://virt10.itu.chalmers.se/index.php/Card_Building",
   "Cards":"http://virt10.itu.chalmers.se/index.php/Cards",
   "Casual Gameplay":"http://virt10.itu.chalmers.se/index.php/Casual_Gameplay",
   "Challenging Gameplay":"http://virt10.itu.chalmers.se/index.php/Challenging_Gameplay",
   "Changes in Perception of Real World Phenomena due to Gameplay":"http://virt10.itu.chalmers.se/index.php/Changes_in_Perception_of_Real_World_Phenomena_due_to_Gameplay",
   "Character Alignments":"http://virt10.itu.chalmers.se/index.php/Character_Alignments",
   "Character Defining Actions":"http://virt10.itu.chalmers.se/index.php/Character_Defining_Actions",
   "Character Development":"http://virt10.itu.chalmers.se/index.php/Character_Development",
   "Character Levels":"http://virt10.itu.chalmers.se/index.php/Character_Levels",
   "Characteristics":"http://virt10.itu.chalmers.se/index.php/Characteristics",
   "Characters":"http://virt10.itu.chalmers.se/index.php/Characters",
   "Chargers":"http://virt10.itu.chalmers.se/index.php/Chargers",
   "Chat Channels":"http://virt10.itu.chalmers.se/index.php/Chat_Channels",
   "Check Points":"http://virt10.itu.chalmers.se/index.php/Check_Points",
   "Choke Points":"http://virt10.itu.chalmers.se/index.php/Choke_Points",
   "Clickability":"http://virt10.itu.chalmers.se/index.php/Clickability",
   "Closure Points":"http://virt10.itu.chalmers.se/index.php/Closure_Points",
   "Clues":"http://virt10.itu.chalmers.se/index.php/Clues",
   "Coaches":"http://virt10.itu.chalmers.se/index.php/Coaches",
   "Collaborative Actions":"http://virt10.itu.chalmers.se/index.php/Collaborative_Actions",
   "Collectible Card Games":"http://virt10.itu.chalmers.se/index.php/Collectible_Card_Games",
   "Combat":"http://virt10.itu.chalmers.se/index.php/Combat",
   "Combos":"http://virt10.itu.chalmers.se/index.php/Combos",
   "Committed Goals":"http://virt10.itu.chalmers.se/index.php/Committed_Goals",
   "Communication Channels":"http://virt10.itu.chalmers.se/index.php/Communication_Channels",
   "Companion Quests":"http://virt10.itu.chalmers.se/index.php/Companion_Quests",
   "Companions":"http://virt10.itu.chalmers.se/index.php/Companions",
   "Competence Areas":"http://virt10.itu.chalmers.se/index.php/Competence_Areas",
   "Complete Resource Depletion":"http://virt10.itu.chalmers.se/index.php/Complete_Resource_Depletion",
   "Complex Gameplay":"http://virt10.itu.chalmers.se/index.php/Complex_Gameplay",
   "Conceal":"http://virt10.itu.chalmers.se/index.php/Conceal",
   "Conditional Passageways":"http://virt10.itu.chalmers.se/index.php/Conditional_Passageways",
   "Configurable Gameplay Areas":"http://virt10.itu.chalmers.se/index.php/Configurable_Gameplay_Areas",
   "Configuration":"http://virt10.itu.chalmers.se/index.php/Configuration",
   "Construction":"http://virt10.itu.chalmers.se/index.php/Construction",
   "Construction/Scoring Phase Shift":"http://virt10.itu.chalmers.se/index.php/Construction/Scoring_Phase_Shift",
   "Context Dependent Reactions":"http://virt10.itu.chalmers.se/index.php/Context_Dependent_Reactions",
   "Contextualization":"http://virt10.itu.chalmers.se/index.php/Contextualization",
   "Contextualized Conversational Responses":"http://virt10.itu.chalmers.se/index.php/Contextualized_Conversational_Responses",
   "Continuous Goals":"http://virt10.itu.chalmers.se/index.php/Continuous_Goals",
   "Controllers":"http://virt10.itu.chalmers.se/index.php/Controllers",
   "Cooldown":"http://virt10.itu.chalmers.se/index.php/Cooldown",
   "Cooperation":"http://virt10.itu.chalmers.se/index.php/Cooperation",
   "Cosmetic Game Items":"http://virt10.itu.chalmers.se/index.php/Cosmetic_Game_Items",
   "Coupled Games":"http://virt10.itu.chalmers.se/index.php/Coupled_Games",
   "Crafting":"http://virt10.itu.chalmers.se/index.php/Crafting",
   "Critical Failures":"http://virt10.itu.chalmers.se/index.php/Critical_Failures",
   "Critical Gameplay Design":"http://virt10.itu.chalmers.se/index.php/Critical_Gameplay_Design",
   "Critical Hits":"http://virt10.itu.chalmers.se/index.php/Critical_Hits",
   "Critical Misses":"http://virt10.itu.chalmers.se/index.php/Critical_Misses",
   "Critical Results":"http://virt10.itu.chalmers.se/index.php/Critical_Results",
   "Critical Successes":"http://virt10.itu.chalmers.se/index.php/Critical_Successes",
   "Crosshairs":"http://virt10.itu.chalmers.se/index.php/Crosshairs",
   "Crossmedia Gameplay":"http://virt10.itu.chalmers.se/index.php/Crossmedia_Gameplay",
   "Current Player Tokens":"http://virt10.itu.chalmers.se/index.php/Current_Player_Tokens",
   "Cutscenes":"http://virt10.itu.chalmers.se/index.php/Cutscenes",
   "Cycle Deck Engines":"http://virt10.itu.chalmers.se/index.php/Cycle_Deck_Engines",
   "Damage":"http://virt10.itu.chalmers.se/index.php/Damage",
   "Death Consequences":"http://virt10.itu.chalmers.se/index.php/Death_Consequences",
   "Deck Building":"http://virt10.itu.chalmers.se/index.php/Deck_Building",
   "Decks":"http://virt10.itu.chalmers.se/index.php/Decks",
   "Decreased Abilities":"http://virt10.itu.chalmers.se/index.php/Decreased_Abilities",
   "Dedicated Game Facilitators":"http://virt10.itu.chalmers.se/index.php/Dedicated_Game_Facilitators",
   "Delayed Effects":"http://virt10.itu.chalmers.se/index.php/Delayed_Effects",
   "Delayed Reciprocity":"http://virt10.itu.chalmers.se/index.php/Delayed_Reciprocity",
   "Destructible Objects":"http://virt10.itu.chalmers.se/index.php/Destructible_Objects",
   "Detective Structures":"http://virt10.itu.chalmers.se/index.php/Detective_Structures",
   "Deterioration":"http://virt10.itu.chalmers.se/index.php/Deterioration",
   "Determinable Chance to Succeed":"http://virt10.itu.chalmers.se/index.php/Determinable_Chance_to_Succeed",
   "Development Time":"http://virt10.itu.chalmers.se/index.php/Development_Time",
   "Dexterity-Based Actions":"http://virt10.itu.chalmers.se/index.php/Dexterity-Based_Actions",
   "Dialogues":"http://virt10.itu.chalmers.se/index.php/Dialogues",
   "Dice":"http://virt10.itu.chalmers.se/index.php/Dice",
   "Diegetic Communication":"http://virt10.itu.chalmers.se/index.php/Diegetic_Communication",
   "Diegetic Consistency":"http://virt10.itu.chalmers.se/index.php/Diegetic_Consistency",
   "Diegetically Outstanding Features":"http://virt10.itu.chalmers.se/index.php/Diegetically_Outstanding_Features",
   "Diegetically Tangible Game Items":"http://virt10.itu.chalmers.se/index.php/Diegetically_Tangible_Game_Items",
   "Difficulty Levels":"http://virt10.itu.chalmers.se/index.php/Difficulty_Levels",
   "Discard Piles":"http://virt10.itu.chalmers.se/index.php/Discard_Piles",
   "Downtime":"http://virt10.itu.chalmers.se/index.php/Downtime",
   "Drafting":"http://virt10.itu.chalmers.se/index.php/Drafting",
   "Drafting Spreads":"http://virt10.itu.chalmers.se/index.php/Drafting_Spreads",
   "Drawing Stacks":"http://virt10.itu.chalmers.se/index.php/Drawing_Stacks",
   "Drop-In/Drop-Out":"http://virt10.itu.chalmers.se/index.php/Drop-In/Drop-Out",
   "Dynamic Difficulty Adjustment":"http://virt10.itu.chalmers.se/index.php/Dynamic_Difficulty_Adjustment",
   "Dynamic Goal Characteristics":"http://virt10.itu.chalmers.se/index.php/Dynamic_Goal_Characteristics",
   "Early Elimination":"http://virt10.itu.chalmers.se/index.php/Early_Elimination",
   "Early Leaving Players":"http://virt10.itu.chalmers.se/index.php/Early_Leaving_Players",
   "Easter Eggs":"http://virt10.itu.chalmers.se/index.php/Easter_Eggs",
   "Eliminate":"http://virt10.itu.chalmers.se/index.php/Eliminate",
   "Emotes":"http://virt10.itu.chalmers.se/index.php/Emotes",
   "Emotional Attachment":"http://virt10.itu.chalmers.se/index.php/Emotional_Attachment",
   "Enactment":"http://virt10.itu.chalmers.se/index.php/Enactment",
   "Enclosure":"http://virt10.itu.chalmers.se/index.php/Enclosure",
   "Encouraged Return Visits":"http://virt10.itu.chalmers.se/index.php/Encouraged_Return_Visits",
   "End State Scoring":"http://virt10.itu.chalmers.se/index.php/End_State_Scoring",
   "Endgame":"http://virt10.itu.chalmers.se/index.php/Endgame",
   "Endgame Quests":"http://virt10.itu.chalmers.se/index.php/Endgame_Quests",
   "Enemies":"http://virt10.itu.chalmers.se/index.php/Enemies",
   "Energy Penalties":"http://virt10.itu.chalmers.se/index.php/Energy_Penalties",
   "Enforced Agent Behavior":"http://virt10.itu.chalmers.se/index.php/Enforced_Agent_Behavior",
   "Enforced Player Anonymity":"http://virt10.itu.chalmers.se/index.php/Enforced_Player_Anonymity",
   "Entitled Players":"http://virt10.itu.chalmers.se/index.php/Entitled_Players",
   "Entrenching Gameplay":"http://virt10.itu.chalmers.se/index.php/Entrenching_Gameplay",
   "Environmental Effects":"http://virt10.itu.chalmers.se/index.php/Environmental_Effects",
   "Environmental Storytelling":"http://virt10.itu.chalmers.se/index.php/Environmental_Storytelling",
   "Ephemeral Events":"http://virt10.itu.chalmers.se/index.php/Ephemeral_Events",
   "Ephemeral Goals":"http://virt10.itu.chalmers.se/index.php/Ephemeral_Goals",
   "Equipment":"http://virt10.itu.chalmers.se/index.php/Equipment",
   "Equipment Slots":"http://virt10.itu.chalmers.se/index.php/Equipment_Slots",
   "Evade":"http://virt10.itu.chalmers.se/index.php/Evade",
   "Events Timed to the Real World":"http://virt10.itu.chalmers.se/index.php/Events_Timed_to_the_Real_World",
   "Ever Increasing Difficulty":"http://virt10.itu.chalmers.se/index.php/Ever_Increasing_Difficulty",
   "Evolving Rule Sets":"http://virt10.itu.chalmers.se/index.php/Evolving_Rule_Sets",
   "Exaggerated Perception of Influence":"http://virt10.itu.chalmers.se/index.php/Exaggerated_Perception_of_Influence",
   "Exceptional Events":"http://virt10.itu.chalmers.se/index.php/Exceptional_Events",
   "Excise":"http://virt10.itu.chalmers.se/index.php/Excise",
   "Excluding Goals":"http://virt10.itu.chalmers.se/index.php/Excluding_Goals",
   "Expansion":"http://virt10.itu.chalmers.se/index.php/Expansion",
   "Experimenting":"http://virt10.itu.chalmers.se/index.php/Experimenting",
   "Explicit Random Seeds":"http://virt10.itu.chalmers.se/index.php/Explicit_Random_Seeds",
   "Exploitation":"http://virt10.itu.chalmers.se/index.php/Exploitation",
   "Extended Actions":"http://virt10.itu.chalmers.se/index.php/Extended_Actions",
   "Extermination":"http://virt10.itu.chalmers.se/index.php/Extermination",
   "Extra Chances":"http://virt10.itu.chalmers.se/index.php/Extra_Chances",
   "Extra Turns":"http://virt10.itu.chalmers.se/index.php/Extra_Turns",
   "Extra-Game Actions":"http://virt10.itu.chalmers.se/index.php/Extra-Game_Actions",
   "Extra-Game Broadcasting":"http://virt10.itu.chalmers.se/index.php/Extra-Game_Broadcasting",
   "Extra-Game Consequences":"http://virt10.itu.chalmers.se/index.php/Extra-Game_Consequences",
   "Extra-Game Input":"http://virt10.itu.chalmers.se/index.php/Extra-Game_Input",
   "Facilitating Rewards":"http://virt10.itu.chalmers.se/index.php/Facilitating_Rewards",
   "Factions":"http://virt10.itu.chalmers.se/index.php/Factions",
   "Fake Game Cancellations":"http://virt10.itu.chalmers.se/index.php/Fake_Game_Cancellations",
   "Fake Game Overs":"http://virt10.itu.chalmers.se/index.php/Fake_Game_Overs",
   "Feelies":"http://virt10.itu.chalmers.se/index.php/Feelies",
   "Feigned Die Rolls":"http://virt10.itu.chalmers.se/index.php/Feigned_Die_Rolls",
   "Finale Levels":"http://virt10.itu.chalmers.se/index.php/Finale_Levels",
   "First Player Advantages":"http://virt10.itu.chalmers.se/index.php/First_Player_Advantages",
   "First Player Tokens":"http://virt10.itu.chalmers.se/index.php/First_Player_Tokens",
   "First-Person Views":"http://virt10.itu.chalmers.se/index.php/First-Person_Views",
   "Fixed Distributions":"http://virt10.itu.chalmers.se/index.php/Fixed_Distributions",
   "Flanking Routes":"http://virt10.itu.chalmers.se/index.php/Flanking_Routes",
   "Flip-Flop Events":"http://virt10.itu.chalmers.se/index.php/Flip-Flop_Events",
   "Focus Loci":"http://virt10.itu.chalmers.se/index.php/Focus_Loci",
   "Fog of War":"http://virt10.itu.chalmers.se/index.php/Fog_of_War",
   "Framed Freedom":"http://virt10.itu.chalmers.se/index.php/Framed_Freedom",
   "Free Game Element Manipulation":"http://virt10.itu.chalmers.se/index.php/Free_Game_Element_Manipulation",
   "Free Gift Inventories":"http://virt10.itu.chalmers.se/index.php/Free_Gift_Inventories",
   "Freedom of Choice":"http://virt10.itu.chalmers.se/index.php/Freedom_of_Choice",
   "Friend Lists":"http://virt10.itu.chalmers.se/index.php/Friend_Lists",
   "Friendly Fire":"http://virt10.itu.chalmers.se/index.php/Friendly_Fire",
   "FUBAR Enjoyment":"http://virt10.itu.chalmers.se/index.php/FUBAR_Enjoyment",
   "Fudged Results":"http://virt10.itu.chalmers.se/index.php/Fudged_Results",
   "Functional Roles":"http://virt10.itu.chalmers.se/index.php/Functional_Roles",
   "Further Player Improvement Potential":"http://virt10.itu.chalmers.se/index.php/Further_Player_Improvement_Potential",
   "Gain Competence":"http://virt10.itu.chalmers.se/index.php/Gain_Competence",
   "Gain Information":"http://virt10.itu.chalmers.se/index.php/Gain_Information",
   "Gain Ownership":"http://virt10.itu.chalmers.se/index.php/Gain_Ownership",
   "Galleries":"http://virt10.itu.chalmers.se/index.php/Galleries",
   "Game Boards":"http://virt10.itu.chalmers.se/index.php/Game_Boards",
   "Game Element Insertion":"http://virt10.itu.chalmers.se/index.php/Game_Element_Insertion",
   "Game Element Trading":"http://virt10.itu.chalmers.se/index.php/Game_Element_Trading",
   "Game Instance Stories":"http://virt10.itu.chalmers.se/index.php/Game_Instance_Stories",
   "Game Items":"http://virt10.itu.chalmers.se/index.php/Game_Items",
   "Game Lobbies":"http://virt10.itu.chalmers.se/index.php/Game_Lobbies",
   "Game Masters":"http://virt10.itu.chalmers.se/index.php/Game_Masters",
   "Game Over":"http://virt10.itu.chalmers.se/index.php/Game_Over",
   "Game Pauses":"http://virt10.itu.chalmers.se/index.php/Game_Pauses",
   "Game Servers":"http://virt10.itu.chalmers.se/index.php/Game_Servers",
   "Game State Indicators":"http://virt10.itu.chalmers.se/index.php/Game_State_Indicators",
   "Game State Overviews":"http://virt10.itu.chalmers.se/index.php/Game_State_Overviews",
   "Game System Player":"http://virt10.itu.chalmers.se/index.php/Game_System_Player",
   "Game Termination Penalties":"http://virt10.itu.chalmers.se/index.php/Game_Termination_Penalties",
   "Game Time Manipulation":"http://virt10.itu.chalmers.se/index.php/Game_Time_Manipulation",
   "Game World Exploration":"http://virt10.itu.chalmers.se/index.php/Game_World_Exploration",
   "Game World Navigation":"http://virt10.itu.chalmers.se/index.php/Game_World_Navigation",
   "Game Worlds":"http://virt10.itu.chalmers.se/index.php/Game_Worlds",
   "Gameplay Engines":"http://virt10.itu.chalmers.se/index.php/Gameplay_Engines",
   "Gameplay Mastery":"http://virt10.itu.chalmers.se/index.php/Gameplay_Mastery",
   "Gameplay Statistics":"http://virt10.itu.chalmers.se/index.php/Gameplay_Statistics",
   "Gamer Mode":"http://virt10.itu.chalmers.se/index.php/Gamer_Mode",
   "Generic Adversaries":"http://virt10.itu.chalmers.se/index.php/Generic_Adversaries",
   "Geometric Progression":"http://virt10.itu.chalmers.se/index.php/Geometric_Progression",
   "Geospatial Game Widgets":"http://virt10.itu.chalmers.se/index.php/Geospatial_Game_Widgets",
   "Ghosts":"http://virt10.itu.chalmers.se/index.php/Ghosts",
   "Goal Achievements":"http://virt10.itu.chalmers.se/index.php/Goal_Achievements",
   "Goal Hierarchies":"http://virt10.itu.chalmers.se/index.php/Goal_Hierarchies",
   "Goal Indicators":"http://virt10.itu.chalmers.se/index.php/Goal_Indicators",
   "Goal-Driven Personal Development":"http://virt10.itu.chalmers.se/index.php/Goal-Driven_Personal_Development",
   "God Fingers":"http://virt10.itu.chalmers.se/index.php/God_Fingers",
   "God Views":"http://virt10.itu.chalmers.se/index.php/God_Views",
   "Gossip":"http://virt10.itu.chalmers.se/index.php/Gossip",
   "Grind Achievements":"http://virt10.itu.chalmers.se/index.php/Grind_Achievements",
   "Grinding":"http://virt10.itu.chalmers.se/index.php/Grinding",
   "Guard":"http://virt10.itu.chalmers.se/index.php/Guard",
   "Guilting":"http://virt10.itu.chalmers.se/index.php/Guilting",
   "Handicap Achievements":"http://virt10.itu.chalmers.se/index.php/Handicap_Achievements",
   "Handicap Systems":"http://virt10.itu.chalmers.se/index.php/Handicap_Systems",
   "Handles":"http://virt10.itu.chalmers.se/index.php/Handles",
   "Hands":"http://virt10.itu.chalmers.se/index.php/Hands",
   "Health":"http://virt10.itu.chalmers.se/index.php/Health",
   "Helpers":"http://virt10.itu.chalmers.se/index.php/Helpers",
   "Helplessness":"http://virt10.itu.chalmers.se/index.php/Helplessness",
   "Herd":"http://virt10.itu.chalmers.se/index.php/Herd",
   "Heterogeneous Game Element Ownership":"http://virt10.itu.chalmers.se/index.php/Heterogeneous_Game_Element_Ownership",
   "Hiding Places":"http://virt10.itu.chalmers.se/index.php/Hiding_Places",
   "High Score Lists":"http://virt10.itu.chalmers.se/index.php/High_Score_Lists",
   "Higher-Level Closures as Gameplay Progresses":"http://virt10.itu.chalmers.se/index.php/Higher-Level_Closures_as_Gameplay_Progresses",
   "Hotseating":"http://virt10.itu.chalmers.se/index.php/Hotseating",
   "Hovering Closures":"http://virt10.itu.chalmers.se/index.php/Hovering_Closures",
   "HUD Interfaces":"http://virt10.itu.chalmers.se/index.php/HUD_Interfaces",
   "Hybrid Gameplay Spaces":"http://virt10.itu.chalmers.se/index.php/Hybrid_Gameplay_Spaces",
   "Illusion of Open Space":"http://virt10.itu.chalmers.se/index.php/Illusion_of_Open_Space",
   "Illusionary Rewards":"http://virt10.itu.chalmers.se/index.php/Illusionary_Rewards",
   "Improved Abilities":"http://virt10.itu.chalmers.se/index.php/Improved_Abilities",
   "Inaccessible Areas":"http://virt10.itu.chalmers.se/index.php/Inaccessible_Areas",
   "Incompatible Goals":"http://virt10.itu.chalmers.se/index.php/Incompatible_Goals",
   "Increasing Rewards":"http://virt10.itu.chalmers.se/index.php/Increasing_Rewards",
   "Individual Penalties":"http://virt10.itu.chalmers.se/index.php/Individual_Penalties",
   "Individual Rewards":"http://virt10.itu.chalmers.se/index.php/Individual_Rewards",
   "Information Passing":"http://virt10.itu.chalmers.se/index.php/Information_Passing",
   "Initiative":"http://virt10.itu.chalmers.se/index.php/Initiative",
   "Installations":"http://virt10.itu.chalmers.se/index.php/Installations",
   "Instances":"http://virt10.itu.chalmers.se/index.php/Instances",
   "Interferable Goals":"http://virt10.itu.chalmers.se/index.php/Interferable_Goals",
   "Internal Conflicts":"http://virt10.itu.chalmers.se/index.php/Internal_Conflicts",
   "Internal Rivalry":"http://virt10.itu.chalmers.se/index.php/Internal_Rivalry",
   "Interruptibility":"http://virt10.itu.chalmers.se/index.php/Interruptibility",
   "Interruptible Actions":"http://virt10.itu.chalmers.se/index.php/Interruptible_Actions",
   "Inventories":"http://virt10.itu.chalmers.se/index.php/Inventories",
   "Investments":"http://virt10.itu.chalmers.se/index.php/Investments",
   "Invisible Walls":"http://virt10.itu.chalmers.se/index.php/Invisible_Walls",
   "Invites":"http://virt10.itu.chalmers.se/index.php/Invites",
   "Invulnerabilities":"http://virt10.itu.chalmers.se/index.php/Invulnerabilities",
   "Irreversible Events":"http://virt10.itu.chalmers.se/index.php/Irreversible_Events",
   "Killcams":"http://virt10.itu.chalmers.se/index.php/Killcams",
   "Kingmaker":"http://virt10.itu.chalmers.se/index.php/Kingmaker",
   "Landmarks":"http://virt10.itu.chalmers.se/index.php/Landmarks",
   "Laning":"http://virt10.itu.chalmers.se/index.php/Laning",
   "Last Man Standing":"http://virt10.itu.chalmers.se/index.php/Last_Man_Standing",
   "Late Arriving Players":"http://virt10.itu.chalmers.se/index.php/Late_Arriving_Players",
   "Legacy Games":"http://virt10.itu.chalmers.se/index.php/Legacy_Games",
   "Levels":"http://virt10.itu.chalmers.se/index.php/Levels",
   "Life Penalties":"http://virt10.itu.chalmers.se/index.php/Life_Penalties",
   "Line of Sight":"http://virt10.itu.chalmers.se/index.php/Line_of_Sight",
   "Live Action Roleplaying":"http://virt10.itu.chalmers.se/index.php/Live_Action_Roleplaying",
   "Lives":"http://virt10.itu.chalmers.se/index.php/Lives",
   "Loading Hints":"http://virt10.itu.chalmers.se/index.php/Loading_Hints",
   "Location-Fixed Abilities":"http://virt10.itu.chalmers.se/index.php/Location-Fixed_Abilities",
   "Loot":"http://virt10.itu.chalmers.se/index.php/Loot",
   "Loyalty":"http://virt10.itu.chalmers.se/index.php/Loyalty",
   "Luck":"http://virt10.itu.chalmers.se/index.php/Luck",
   "Lucky Guess Solutions":"http://virt10.itu.chalmers.se/index.php/Lucky_Guess_Solutions",
   "Lull Periods":"http://virt10.itu.chalmers.se/index.php/Lull_Periods",
   "MacGuffins":"http://virt10.itu.chalmers.se/index.php/MacGuffins",
   "Main Quests":"http://virt10.itu.chalmers.se/index.php/Main_Quests",
   "Maneuvering":"http://virt10.itu.chalmers.se/index.php/Maneuvering",
   "Massively Multiplayer Online Games":"http://virt10.itu.chalmers.se/index.php/Massively_Multiplayer_Online_Games",
   "Massively Single-Player Online Games":"http://virt10.itu.chalmers.se/index.php/Massively_Single-Player_Online_Games",
   "Mediated Gameplay":"http://virt10.itu.chalmers.se/index.php/Mediated_Gameplay",
   "Melodramatic Structures":"http://virt10.itu.chalmers.se/index.php/Melodramatic_Structures",
   "Memorabilia":"http://virt10.itu.chalmers.se/index.php/Memorabilia",
   "Memorizing":"http://virt10.itu.chalmers.se/index.php/Memorizing",
   "Memory of Important Events":"http://virt10.itu.chalmers.se/index.php/Memory_of_Important_Events",
   "Meta Games":"http://virt10.itu.chalmers.se/index.php/Meta_Games",
   "Meta Servers":"http://virt10.itu.chalmers.se/index.php/Meta_Servers",
   "Meta-Postures":"http://virt10.itu.chalmers.se/index.php/Meta-Postures",
   "Meta-Techniques":"http://virt10.itu.chalmers.se/index.php/Meta-Techniques",
   "Middlegame":"http://virt10.itu.chalmers.se/index.php/Middlegame",
   "Mimetic Interfaces":"http://virt10.itu.chalmers.se/index.php/Mimetic_Interfaces",
   "Mini-maps":"http://virt10.itu.chalmers.se/index.php/Mini-maps",
   "Minigames":"http://virt10.itu.chalmers.se/index.php/Minigames",
   "Minimalized Social Weight":"http://virt10.itu.chalmers.se/index.php/Minimalized_Social_Weight",
   "Misfortune Mitigation":"http://virt10.itu.chalmers.se/index.php/Misfortune_Mitigation",
   "Moveable Tiles":"http://virt10.itu.chalmers.se/index.php/Moveable_Tiles",
   "Movement":"http://virt10.itu.chalmers.se/index.php/Movement",
   "Movement Limitations":"http://virt10.itu.chalmers.se/index.php/Movement_Limitations",
   "Mules":"http://virt10.itu.chalmers.se/index.php/Mules",
   "Multiplayer Games":"http://virt10.itu.chalmers.se/index.php/Multiplayer_Games",
   "Mutual FUBAR Enjoyment":"http://virt10.itu.chalmers.se/index.php/Mutual_FUBAR_Enjoyment",
   "Mutual Goals":"http://virt10.itu.chalmers.se/index.php/Mutual_Goals",
   "Narration Structures":"http://virt10.itu.chalmers.se/index.php/Narration_Structures",
   "Near Miss Indicators":"http://virt10.itu.chalmers.se/index.php/Near_Miss_Indicators",
   "Negative Feedback Loops":"http://virt10.itu.chalmers.se/index.php/Negative_Feedback_Loops",
   "Negotiable Game Instance Duration":"http://virt10.itu.chalmers.se/index.php/Negotiable_Game_Instance_Duration",
   "Negotiable Game Sessions":"http://virt10.itu.chalmers.se/index.php/Negotiable_Game_Sessions",
   "Negotiable Play Sessions":"http://virt10.itu.chalmers.se/index.php/Negotiable_Play_Sessions",
   "New Abilities":"http://virt10.itu.chalmers.se/index.php/New_Abilities",
   "Ninja Looting":"http://virt10.itu.chalmers.se/index.php/Ninja_Looting",
   "No Direct Player Influence":"http://virt10.itu.chalmers.se/index.php/No_Direct_Player_Influence",
   "No-Ops":"http://virt10.itu.chalmers.se/index.php/No-Ops",
   "No-Use Bonus":"http://virt10.itu.chalmers.se/index.php/No-Use_Bonus",
   "Non-Consistent Narration":"http://virt10.itu.chalmers.se/index.php/Non-Consistent_Narration",
   "Non-Diegetic Communication":"http://virt10.itu.chalmers.se/index.php/Non-Diegetic_Communication",
   "Non-Diegetic Features":"http://virt10.itu.chalmers.se/index.php/Non-Diegetic_Features",
   "Non-Localized Resources":"http://virt10.itu.chalmers.se/index.php/Non-Localized_Resources",
   "Non-Player Characters":"http://virt10.itu.chalmers.se/index.php/Non-Player_Characters",
   "Non-Player Help":"http://virt10.itu.chalmers.se/index.php/Non-Player_Help",
   "Non-Renewable Resources":"http://virt10.itu.chalmers.se/index.php/Non-Renewable_Resources",
   "Obstacles":"http://virt10.itu.chalmers.se/index.php/Obstacles",
   "Open Destiny":"http://virt10.itu.chalmers.se/index.php/Open_Destiny",
   "Open-Ended Die Rolls":"http://virt10.itu.chalmers.se/index.php/Open-Ended_Die_Rolls",
   "Optional Goals":"http://virt10.itu.chalmers.se/index.php/Optional_Goals",
   "Optional Rules":"http://virt10.itu.chalmers.se/index.php/Optional_Rules",
   "Orthogonal Differentiation":"http://virt10.itu.chalmers.se/index.php/Orthogonal_Differentiation",
   "Outcome Indicators":"http://virt10.itu.chalmers.se/index.php/Outcome_Indicators",
   "Own Agenda":"http://virt10.itu.chalmers.se/index.php/Own_Agenda",
   "Parallel Lives":"http://virt10.itu.chalmers.se/index.php/Parallel_Lives",
   "Parties":"http://virt10.itu.chalmers.se/index.php/Parties",
   "Password Save Files":"http://virt10.itu.chalmers.se/index.php/Password_Save_Files",
   "Pay to Play":"http://virt10.itu.chalmers.se/index.php/Pay_to_Play",
   "Penalties":"http://virt10.itu.chalmers.se/index.php/Penalties",
   "Performance Uncertainty":"http://virt10.itu.chalmers.se/index.php/Performance_Uncertainty",
   "Permadeath":"http://virt10.itu.chalmers.se/index.php/Permadeath",
   "Persistent Game World Changes":"http://virt10.itu.chalmers.se/index.php/Persistent_Game_World_Changes",
   "Persistent Game Worlds":"http://virt10.itu.chalmers.se/index.php/Persistent_Game_Worlds",
   "Perspective Taking":"http://virt10.itu.chalmers.se/index.php/Perspective_Taking",
   "Pervasive Gameplay":"http://virt10.itu.chalmers.se/index.php/Pervasive_Gameplay",
   "Phasing":"http://virt10.itu.chalmers.se/index.php/Phasing",
   "Physical Enactment":"http://virt10.itu.chalmers.se/index.php/Physical_Enactment",
   "Physical Navigation":"http://virt10.itu.chalmers.se/index.php/Physical_Navigation",
   "Pick-Ups":"http://virt10.itu.chalmers.se/index.php/Pick-Ups",
   "Picture-in-Picture Views":"http://virt10.itu.chalmers.se/index.php/Picture-in-Picture_Views",
   "Player Agency":"http://virt10.itu.chalmers.se/index.php/Player_Agency",
   "Player Aids":"http://virt10.itu.chalmers.se/index.php/Player_Aids",
   "Player Anonymity":"http://virt10.itu.chalmers.se/index.php/Player_Anonymity",
   "Player Augmentations":"http://virt10.itu.chalmers.se/index.php/Player_Augmentations",
   "Player Balance":"http://virt10.itu.chalmers.se/index.php/Player_Balance",
   "Player Characters":"http://virt10.itu.chalmers.se/index.php/Player_Characters",
   "Player Created Game Elements":"http://virt10.itu.chalmers.se/index.php/Player_Created_Game_Elements",
   "Player Elimination":"http://virt10.itu.chalmers.se/index.php/Player_Elimination",
   "Player Kicking":"http://virt10.itu.chalmers.se/index.php/Player_Kicking",
   "Player Killing":"http://virt10.itu.chalmers.se/index.php/Player_Killing",
   "Player Physical Prowess":"http://virt10.itu.chalmers.se/index.php/Player_Physical_Prowess",
   "Player Unpredictability":"http://virt10.itu.chalmers.se/index.php/Player_Unpredictability",
   "Player-Artifact Proximity":"http://virt10.itu.chalmers.se/index.php/Player-Artifact_Proximity",
   "Player-Avatar Proximity":"http://virt10.itu.chalmers.se/index.php/Player-Avatar_Proximity",
   "Player-Created Characters":"http://virt10.itu.chalmers.se/index.php/Player-Created_Characters",
   "Player-Defined Goals":"http://virt10.itu.chalmers.se/index.php/Player-Defined_Goals",
   "Player-Location Proximity":"http://virt10.itu.chalmers.se/index.php/Player-Location_Proximity",
   "Player-Planned Development":"http://virt10.itu.chalmers.se/index.php/Player-Planned_Development",
   "Player-Player Proximity":"http://virt10.itu.chalmers.se/index.php/Player-Player_Proximity",
   "Player/Character Awareness Consistency":"http://virt10.itu.chalmers.se/index.php/Player/Character_Awareness_Consistency",
   "Player/Character Skill Composites":"http://virt10.itu.chalmers.se/index.php/Player/Character_Skill_Composites",
   "Playing to Lose":"http://virt10.itu.chalmers.se/index.php/Playing_to_Lose",
   "Point of Interest Indicators":"http://virt10.itu.chalmers.se/index.php/Point_of_Interest_Indicators",
   "Polyathlons":"http://virt10.itu.chalmers.se/index.php/Polyathlons",
   "Positive Feedback Loops":"http://virt10.itu.chalmers.se/index.php/Positive_Feedback_Loops",
   "Possibility of Anonymity":"http://virt10.itu.chalmers.se/index.php/Possibility_of_Anonymity",
   "Possibility of Graceful Surrender":"http://virt10.itu.chalmers.se/index.php/Possibility_of_Graceful_Surrender",
   "Pottering":"http://virt10.itu.chalmers.se/index.php/Pottering",
   "Power-Ups":"http://virt10.itu.chalmers.se/index.php/Power-Ups",
   "Predefined Goals":"http://virt10.itu.chalmers.se/index.php/Predefined_Goals",
   "Predetermined Story Structures":"http://virt10.itu.chalmers.se/index.php/Predetermined_Story_Structures",
   "Predictable Consequences":"http://virt10.itu.chalmers.se/index.php/Predictable_Consequences",
   "Predictable Winner":"http://virt10.itu.chalmers.se/index.php/Predictable_Winner",
   "Preventing Goals":"http://virt10.itu.chalmers.se/index.php/Preventing_Goals",
   "Private Game Spaces":"http://virt10.itu.chalmers.se/index.php/Private_Game_Spaces",
   "Privileged Abilities":"http://virt10.itu.chalmers.se/index.php/Privileged_Abilities",
   "Privileged Movement":"http://virt10.itu.chalmers.se/index.php/Privileged_Movement",
   "Procedurally Generated Game Worlds":"http://virt10.itu.chalmers.se/index.php/Procedurally_Generated_Game_Worlds",
   "Progress Indicators":"http://virt10.itu.chalmers.se/index.php/Progress_Indicators",
   "Prompting Techniques":"http://virt10.itu.chalmers.se/index.php/Prompting_Techniques",
   "Props":"http://virt10.itu.chalmers.se/index.php/Props",
   "Public Player Statistics":"http://virt10.itu.chalmers.se/index.php/Public_Player_Statistics",
   "Purchasable Game Advantages":"http://virt10.itu.chalmers.se/index.php/Purchasable_Game_Advantages",
   "Puzzle Solving":"http://virt10.itu.chalmers.se/index.php/Puzzle_Solving",
   "PvE":"http://virt10.itu.chalmers.se/index.php/PvE",
   "PvP":"http://virt10.itu.chalmers.se/index.php/PvP",
   "Quests":"http://virt10.itu.chalmers.se/index.php/Quests",
   "Quick Returns":"http://virt10.itu.chalmers.se/index.php/Quick_Returns",
   "Quick Time Events":"http://virt10.itu.chalmers.se/index.php/Quick_Time_Events",
   "Quick Travel":"http://virt10.itu.chalmers.se/index.php/Quick_Travel",
   "Quizzes":"http://virt10.itu.chalmers.se/index.php/Quizzes",
   "Rabbit Hole Invitations":"http://virt10.itu.chalmers.se/index.php/Rabbit_Hole_Invitations",
   "Races":"http://virt10.itu.chalmers.se/index.php/Races",
   "Ragequitting":"http://virt10.itu.chalmers.se/index.php/Ragequitting",
   "Randomness":"http://virt10.itu.chalmers.se/index.php/Randomness",
   "Real Life Activities Affect Game State":"http://virt10.itu.chalmers.se/index.php/Real_Life_Activities_Affect_Game_State",
   "Real World Gameplay Spaces":"http://virt10.itu.chalmers.se/index.php/Real_World_Gameplay_Spaces",
   "Real World Knowledge Advantages":"http://virt10.itu.chalmers.se/index.php/Real_World_Knowledge_Advantages",
   "Real-Time Games":"http://virt10.itu.chalmers.se/index.php/Real-Time_Games",
   "Reconfigurable Game Worlds":"http://virt10.itu.chalmers.se/index.php/Reconfigurable_Game_Worlds",
   "Reconnaissance":"http://virt10.itu.chalmers.se/index.php/Reconnaissance",
   "Red Herrings":"http://virt10.itu.chalmers.se/index.php/Red_Herrings",
   "Reflective Communication":"http://virt10.itu.chalmers.se/index.php/Reflective_Communication",
   "Regenerating Resources":"http://virt10.itu.chalmers.se/index.php/Regenerating_Resources",
   "Renewable Resources":"http://virt10.itu.chalmers.se/index.php/Renewable_Resources",
   "Repeat Combos":"http://virt10.itu.chalmers.se/index.php/Repeat_Combos",
   "Repetition of Position Draws":"http://virt10.itu.chalmers.se/index.php/Repetition_of_Position_Draws",
   "Repetitive Gameplay":"http://virt10.itu.chalmers.se/index.php/Repetitive_Gameplay",
   "Replayability":"http://virt10.itu.chalmers.se/index.php/Replayability",
   "Replays":"http://virt10.itu.chalmers.se/index.php/Replays",
   "Rescue":"http://virt10.itu.chalmers.se/index.php/Rescue",
   "Reserves":"http://virt10.itu.chalmers.se/index.php/Reserves",
   "Resource Caps":"http://virt10.itu.chalmers.se/index.php/Resource_Caps",
   "Resource Competition":"http://virt10.itu.chalmers.se/index.php/Resource_Competition",
   "Resource Locations":"http://virt10.itu.chalmers.se/index.php/Resource_Locations",
   "Resource Sources":"http://virt10.itu.chalmers.se/index.php/Resource_Sources",
   "Resources":"http://virt10.itu.chalmers.se/index.php/Resources",
   "Revoke Rules":"http://virt10.itu.chalmers.se/index.php/Revoke_Rules",
   "Reward Widgets":"http://virt10.itu.chalmers.se/index.php/Reward_Widgets",
   "Rewards":"http://virt10.itu.chalmers.se/index.php/Rewards",
   "Rhythm-Based Actions":"http://virt10.itu.chalmers.se/index.php/Rhythm-Based_Actions",
   "Robotic Players":"http://virt10.itu.chalmers.se/index.php/Robotic_Players",
   "Role Fulfillment":"http://virt10.itu.chalmers.se/index.php/Role_Fulfillment",
   "Role Selection":"http://virt10.itu.chalmers.se/index.php/Role_Selection",
   "Roleplaying":"http://virt10.itu.chalmers.se/index.php/Roleplaying",
   "Safe Havens":"http://virt10.itu.chalmers.se/index.php/Safe_Havens",
   "Sanctioned Cheating":"http://virt10.itu.chalmers.se/index.php/Sanctioned_Cheating",
   "Save Files":"http://virt10.itu.chalmers.se/index.php/Save_Files",
   "Save Points":"http://virt10.itu.chalmers.se/index.php/Save_Points",
   "Save Scumming":"http://virt10.itu.chalmers.se/index.php/Save_Scumming",
   "Save-Load Cycles":"http://virt10.itu.chalmers.se/index.php/Save-Load_Cycles",
   "Scenes":"http://virt10.itu.chalmers.se/index.php/Scenes",
   "Score Tracks":"http://virt10.itu.chalmers.se/index.php/Score_Tracks",
   "Scores":"http://virt10.itu.chalmers.se/index.php/Scores",
   "Scouting":"http://virt10.itu.chalmers.se/index.php/Scouting",
   "Scripted Information Sequences":"http://virt10.itu.chalmers.se/index.php/Scripted_Information_Sequences",
   "Seamful Gameplay":"http://virt10.itu.chalmers.se/index.php/Seamful_Gameplay",
   "Secondary Interface Screens":"http://virt10.itu.chalmers.se/index.php/Secondary_Interface_Screens",
   "Secret Areas":"http://virt10.itu.chalmers.se/index.php/Secret_Areas",
   "Secret Goals":"http://virt10.itu.chalmers.se/index.php/Secret_Goals",
   "Secret Resources":"http://virt10.itu.chalmers.se/index.php/Secret_Resources",
   "Secret Scoring Mechanisms":"http://virt10.itu.chalmers.se/index.php/Secret_Scoring_Mechanisms",
   "Selectable Set of Goals":"http://virt10.itu.chalmers.se/index.php/Selectable_Set_of_Goals",
   "Self-Facilitated Games":"http://virt10.itu.chalmers.se/index.php/Self-Facilitated_Games",
   "Self-Reported Positioning":"http://virt10.itu.chalmers.se/index.php/Self-Reported_Positioning",
   "Self-Service Kiosks":"http://virt10.itu.chalmers.se/index.php/Self-Service_Kiosks",
   "Sense of Self":"http://virt10.itu.chalmers.se/index.php/Sense_of_Self",
   "Setback Penalties":"http://virt10.itu.chalmers.se/index.php/Setback_Penalties",
   "Sets":"http://virt10.itu.chalmers.se/index.php/Sets",
   "Shared Penalties":"http://virt10.itu.chalmers.se/index.php/Shared_Penalties",
   "Shared Resources":"http://virt10.itu.chalmers.se/index.php/Shared_Resources",
   "Shared Rewards":"http://virt10.itu.chalmers.se/index.php/Shared_Rewards",
   "Shrinking Game Worlds":"http://virt10.itu.chalmers.se/index.php/Shrinking_Game_Worlds",
   "Sidegrades":"http://virt10.itu.chalmers.se/index.php/Sidegrades",
   "Sidequests":"http://virt10.itu.chalmers.se/index.php/Sidequests",
   "Single-Player Games":"http://virt10.itu.chalmers.se/index.php/Single-Player_Games",
   "Skills":"http://virt10.itu.chalmers.se/index.php/Skills",
   "Sniper Locations":"http://virt10.itu.chalmers.se/index.php/Sniper_Locations",
   "Social Adaptability":"http://virt10.itu.chalmers.se/index.php/Social_Adaptability",
   "Social Dilemmas":"http://virt10.itu.chalmers.se/index.php/Social_Dilemmas",
   "Social Rewards":"http://virt10.itu.chalmers.se/index.php/Social_Rewards",
   "Social Roles":"http://virt10.itu.chalmers.se/index.php/Social_Roles",
   "Social Skills":"http://virt10.itu.chalmers.se/index.php/Social_Skills",
   "Sockets":"http://virt10.itu.chalmers.se/index.php/Sockets",
   "Solution Uncertainty":"http://virt10.itu.chalmers.se/index.php/Solution_Uncertainty",
   "Spawn Points":"http://virt10.itu.chalmers.se/index.php/Spawn_Points",
   "Spawning":"http://virt10.itu.chalmers.se/index.php/Spawning",
   "Spectacular Failure Enjoyment":"http://virt10.itu.chalmers.se/index.php/Spectacular_Failure_Enjoyment",
   "Spectators":"http://virt10.itu.chalmers.se/index.php/Spectators",
   "Speedending":"http://virt10.itu.chalmers.se/index.php/Speedending",
   "Speedruns":"http://virt10.itu.chalmers.se/index.php/Speedruns",
   "Split-Screen Views":"http://virt10.itu.chalmers.se/index.php/Split-Screen_Views",
   "Stack Seeding":"http://virt10.itu.chalmers.se/index.php/Stack_Seeding",
   "Startgame":"http://virt10.itu.chalmers.se/index.php/Startgame",
   "Steadily Decreasing Resources":"http://virt10.itu.chalmers.se/index.php/Steadily_Decreasing_Resources",
   "Stealth":"http://virt10.itu.chalmers.se/index.php/Stealth",
   "Stimulated Planning":"http://virt10.itu.chalmers.se/index.php/Stimulated_Planning",
   "Storytelling":"http://virt10.itu.chalmers.se/index.php/Storytelling",
   "Strategic Knowledge":"http://virt10.itu.chalmers.se/index.php/Strategic_Knowledge",
   "Strategic Locations":"http://virt10.itu.chalmers.se/index.php/Strategic_Locations",
   "Strategic Planning":"http://virt10.itu.chalmers.se/index.php/Strategic_Planning",
   "Substitute Actions":"http://virt10.itu.chalmers.se/index.php/Substitute_Actions",
   "Summary Updates":"http://virt10.itu.chalmers.se/index.php/Summary_Updates",
   "Supporting Goals":"http://virt10.itu.chalmers.se/index.php/Supporting_Goals",
   "Surprise Attacks":"http://virt10.itu.chalmers.se/index.php/Surprise_Attacks",
   "Surrendering":"http://virt10.itu.chalmers.se/index.php/Surrendering",
   "Sustenance Rewards":"http://virt10.itu.chalmers.se/index.php/Sustenance_Rewards",
   "Switches":"http://virt10.itu.chalmers.se/index.php/Switches",
   "Symbiotic Player Relations":"http://virt10.itu.chalmers.se/index.php/Symbiotic_Player_Relations",
   "Symmetric Goals":"http://virt10.itu.chalmers.se/index.php/Symmetric_Goals",
   "Synchronous Gameplay":"http://virt10.itu.chalmers.se/index.php/Synchronous_Gameplay",
   "Tactical Planning":"http://virt10.itu.chalmers.se/index.php/Tactical_Planning",
   "Team Accomplishments":"http://virt10.itu.chalmers.se/index.php/Team_Accomplishments",
   "Team Balance":"http://virt10.itu.chalmers.se/index.php/Team_Balance",
   "Team Combos":"http://virt10.itu.chalmers.se/index.php/Team_Combos",
   "Team Development":"http://virt10.itu.chalmers.se/index.php/Team_Development",
   "Team Elimination":"http://virt10.itu.chalmers.se/index.php/Team_Elimination",
   "Team Strategy Identification":"http://virt10.itu.chalmers.se/index.php/Team_Strategy_Identification",
   "Teams":"http://virt10.itu.chalmers.se/index.php/Teams",
   "Temporal Consistency":"http://virt10.itu.chalmers.se/index.php/Temporal_Consistency",
   "Temporary Abilities":"http://virt10.itu.chalmers.se/index.php/Temporary_Abilities",
   "Tension":"http://virt10.itu.chalmers.se/index.php/Tension",
   "Territories":"http://virt10.itu.chalmers.se/index.php/Territories",
   "Testing Achievements":"http://virt10.itu.chalmers.se/index.php/Testing_Achievements",
   "Thematic Consistency":"http://virt10.itu.chalmers.se/index.php/Thematic_Consistency",
   "Third-Person Views":"http://virt10.itu.chalmers.se/index.php/Third-Person_Views",
   "Tick-Based Games":"http://virt10.itu.chalmers.se/index.php/Tick-Based_Games",
   "Tiebreakers":"http://virt10.itu.chalmers.se/index.php/Tiebreakers",
   "Tied Results":"http://virt10.itu.chalmers.se/index.php/Tied_Results",
   "Tiered Participation":"http://virt10.itu.chalmers.se/index.php/Tiered_Participation",
   "Tile-Laying":"http://virt10.itu.chalmers.se/index.php/Tile-Laying",
   "Tiles":"http://virt10.itu.chalmers.se/index.php/Tiles",
   "Time Limited Game Instances":"http://virt10.itu.chalmers.se/index.php/Time_Limited_Game_Instances",
   "Time Limits":"http://virt10.itu.chalmers.se/index.php/Time_Limits",
   "Time Pressure":"http://virt10.itu.chalmers.se/index.php/Time_Pressure",
   "Togetherness":"http://virt10.itu.chalmers.se/index.php/Togetherness",
   "Token Placement":"http://virt10.itu.chalmers.se/index.php/Token_Placement",
   "Tools":"http://virt10.itu.chalmers.se/index.php/Tools",
   "Tooltips":"http://virt10.itu.chalmers.se/index.php/Tooltips",
   "Traces":"http://virt10.itu.chalmers.se/index.php/Traces",
   "Trade-Offs":"http://virt10.itu.chalmers.se/index.php/Trade-Offs",
   "Transferable Items":"http://virt10.itu.chalmers.se/index.php/Transferable_Items",
   "Transport Routes":"http://virt10.itu.chalmers.se/index.php/Transport_Routes",
   "Traps":"http://virt10.itu.chalmers.se/index.php/Traps",
   "Traverse":"http://virt10.itu.chalmers.se/index.php/Traverse",
   "Trial and Error Solutions":"http://virt10.itu.chalmers.se/index.php/Trial_and_Error_Solutions",
   "Trick Taking":"http://virt10.itu.chalmers.se/index.php/Trick_Taking",
   "Trumps":"http://virt10.itu.chalmers.se/index.php/Trumps",
   "Turn Taking":"http://virt10.itu.chalmers.se/index.php/Turn_Taking",
   "Turn-Based Games":"http://virt10.itu.chalmers.se/index.php/Turn-Based_Games",
   "Turnovers":"http://virt10.itu.chalmers.se/index.php/Turnovers",
   "TvT":"http://virt10.itu.chalmers.se/index.php/TvT",
   "Ubiquitous Gameplay":"http://virt10.itu.chalmers.se/index.php/Ubiquitous_Gameplay",
   "Ultra-Powerful Events":"http://virt10.itu.chalmers.se/index.php/Ultra-Powerful_Events",
   "Uncertainty of Information":"http://virt10.itu.chalmers.se/index.php/Uncertainty_of_Information",
   "Uncertainty of Outcome":"http://virt10.itu.chalmers.se/index.php/Uncertainty_of_Outcome",
   "Units":"http://virt10.itu.chalmers.se/index.php/Units",
   "Unknown Goals":"http://virt10.itu.chalmers.se/index.php/Unknown_Goals",
   "Unlocking":"http://virt10.itu.chalmers.se/index.php/Unlocking",
   "Unpredictable Behavior":"http://virt10.itu.chalmers.se/index.php/Unpredictable_Behavior",
   "Unsynchronized Game Sessions":"http://virt10.itu.chalmers.se/index.php/Unsynchronized_Game_Sessions",
   "Unwinnable Game States":"http://virt10.itu.chalmers.se/index.php/Unwinnable_Game_States",
   "Unwinnable Games":"http://virt10.itu.chalmers.se/index.php/Unwinnable_Games",
   "Upgrades":"http://virt10.itu.chalmers.se/index.php/Upgrades",
   "Value of Effort":"http://virt10.itu.chalmers.se/index.php/Value_of_Effort",
   "Variable Accuracy":"http://virt10.itu.chalmers.se/index.php/Variable_Accuracy",
   "Varied Gameplay":"http://virt10.itu.chalmers.se/index.php/Varied_Gameplay",
   "Varying Rule Sets":"http://virt10.itu.chalmers.se/index.php/Varying_Rule_Sets",
   "Varying Turn Orders":"http://virt10.itu.chalmers.se/index.php/Varying_Turn_Orders",
   "Vehicle Sections":"http://virt10.itu.chalmers.se/index.php/Vehicle_Sections",
   "Vehicles":"http://virt10.itu.chalmers.se/index.php/Vehicles",
   "Vision Modes":"http://virt10.itu.chalmers.se/index.php/Vision_Modes",
   "Visits":"http://virt10.itu.chalmers.se/index.php/Visits",
   "Vulnerabilities":"http://virt10.itu.chalmers.se/index.php/Vulnerabilities",
   "Warming-Up Roleplay Exercises":"http://virt10.itu.chalmers.se/index.php/Warming-Up_Roleplay_Exercises",
   "Warp Zones":"http://virt10.itu.chalmers.se/index.php/Warp_Zones",
   "Waves":"http://virt10.itu.chalmers.se/index.php/Waves",
   "Weapons":"http://virt10.itu.chalmers.se/index.php/Weapons",
   "Winner determined after Gameplay Ends":"http://virt10.itu.chalmers.se/index.php/Winner_determined_after_Gameplay_Ends",
   "Winning by Ending Gameplay":"http://virt10.itu.chalmers.se/index.php/Winning_by_Ending_Gameplay",
   "Workshopping":"http://virt10.itu.chalmers.se/index.php/Workshopping",
   "Zero-Player Games":"http://virt10.itu.chalmers.se/index.php/Zero-Player_Games"
}